# Generated by Django 5.0.4 on 2024-04-25 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='selected_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='session',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='personality',
            field=models.CharField(choices=[('op', 'Openness'), ('co', 'Conscientiousness'), ('ex', 'Extraversion'), ('ag', 'Agreeableness'), ('ne', 'Neuroticism')], default='op', max_length=2),
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openness', models.FloatField()),
                ('conscientiousness', models.FloatField()),
                ('extraversion', models.FloatField()),
                ('agreeableness', models.FloatField()),
                ('neuroticism', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
        migrations.DeleteModel(
            name='TestSession',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
