# Generated by Django 5.0.4 on 2024-04-25 19:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_userresponse_selected_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='personality',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='questions.questiocategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
