# Generated by Django 5.0.4 on 2024-04-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questiocategory_remove_question_personality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
    ]
