# Generated by Django 5.0.4 on 2024-04-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade_in_school',
            field=models.CharField(choices=[('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], default='10', max_length=2),
        ),
    ]
